# Meta Data for SEO

## Homepage
title = "Layered Schemas"
#logoImg = "/images/cpl-logo-horizontal-160x32.png"
titleSeparator = ""
titleAddition = ""
description = "Layered schemas: semantic processing for data capture, processing, and exchange. Capture data in multiple languages, improve interoperability, pool data from heterogeneous systems for ELT pipelines, AI, and privacy conscious data exchange"

## Open Graph + Twitter Cards
images = ["images/cpl-logo-horizontal-160x32.png"]
twitterSite = "CPrivacyLabs"
twitterCreator = "CPrivacyLabs"
facebookAuthor = "CloudPrivacyLabs"
facebookPublisher = "CloudPrivacyLabs"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "images/cpl-logo-horizontal-160x32.png"
schemaTwitter = "https://twitter.com/CPrivacyLabs"
schemaLinkedIn = "https://www.linkedin.com/company/cloud-privacy-labs/about/"
schemaGitHub = "https://github.com/cloudprivacylabs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Copyright © Cloud Privacy Labs, LLC"

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = "https://github.com/cloudprivacylabs"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = false
  bootStrapJs = false
  breadCrumb = true
  highLight = true
  kaTex = false
